export { default as Navbar } from './Navbar';
export { default as Footer } from './Footer';
export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Signup } from './Signup';
export { default as About } from './About';
export { default as Contact } from './Contact';
export { default as Service } from './Service';
export { default as Blog } from './Blog';